app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8080:8080"
  volumes:
    - .:/root/swift-helloworld
  command: bash -c "cd /root/swift-helloworld && swift build --clean && swift build && ./.build/debug/Server"
